name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Gradle Wrapper Validation
      uses: gradle/wrapper-validation-action@v1

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Build debug APK
      run: ./gradlew assembleDebug
      
    - name: Run microtests
      run: ./gradlew testDebug
      
  ui-tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run UI tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          arch: x86_64
          target: google_apis
          script: ./gradlew connectedCheck
